name: CI

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    build-and-test:
        name: Build & Unit Tests (Node ${{ matrix.node-version }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20, 22, 24]
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v5

            - name: ⎔ Setup node
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}

            - name: ⎔ Set up pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.14.0

            - name: 📥 Download deps
              run: pnpm install

            - name: 🔨 Build
              run: pnpm build

            - name: 🧪 Run unit tests
              run: pnpm vitest run tests/unit/
