name: GitHub Pages Preview

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    deploy:
        name: Deploy Preview branch on Github.io
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 🥖 Build the React App
              run: |
                  yarn
                  yarn build --filter demo

            - name: Get branch name
              id: branch-name
              uses: tj-actions/branch-names@v5.4

            - name: Running on the default branch.
              run: |
                  echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"

            - name: 🍿 Deploy
              uses: peaceiris/actions-gh-pages@v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./apps/demo/build
                  destination_dir: ./${{ steps.branch-name.outputs.current_branch }}
