name: GitHub Pages Preview

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    deploy:
        name: Deploy Preview branch on Github.io
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Get branch name
              id: branch-name
              uses: tj-actions/branch-names@v5.4

            - name: Set .homepage in package.json
              uses: jossef/action-set-json-field@v2
              with:
                  file: apps/demo/package.json
                  field: homepage
                  value: libraries/${{ steps.branch-name.outputs.current_branch }}

            - name: 🥖 Build the React App
              env:
                  REACT_APP_BASENAME: libraries/${{ steps.branch-name.outputs.current_branch }}
              run: |
                  yarn
                  yarn build --filter demo

            - name: 🍿 Deploy
              uses: peaceiris/actions-gh-pages@v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./apps/demo/build
                  destination_dir: ./${{ steps.branch-name.outputs.current_branch }}

            - name: Link to preview build in PR
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: |
                      Preview app available at <https://crystallizeapi.github.io/${{ steps.branch-name.outputs.current_branch }}>
